version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 5s
      timeout: 5s
      retries: 10

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: odoo
      PGPASSWORD: odoo
    volumes:
      - ./addons:/mnt/addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ["bash", "-lc", "sleep infinity"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: odoo
      PGPASSWORD: odoo
      PYTEST_ADDOPTS: "--cache-clear"
    volumes:
      - ./addons:/mnt/addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./.coveragerc:/mnt/.coveragerc
      - ./pytest.ini:/mnt/pytest.ini
    command: ${OPTIONS}

volumes:
  db_data:
